aws_region = "ap-south-1"
environment = "prod"
product = "terraform"
instance_count = 1
azs = ["ap-south-1a", "ap-south-1b"]
instance_type = "t3.medium"
table_dynamodb = "prod-terraform-lock"
key_dynamodb = "terraform/prod-terraform.tfstate"
backend_bucket = "prod-manage-terraform-state-bucket"