name: Manage Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-aws/**'
      - '.github/workflows/pipeline.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'dev'
        type: string
env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  PRODUCT: ${{ vars.PRODUCT }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  manage-infrastructure:
    name: Validate and Manage Terraform Infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.event.inputs.environment }}  

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Environment Variables
      - name: Set environment variables
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      # Step 2: Configure AWS credentials using IAM role for the selected account
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ENVIRONMENT }}-${{ env.PRODUCT }}-github-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Terraform Init with Workspace Selection
      - name: Terraform Init with Workspace
        run: |
          terraform init
          terraform workspace select ${{ env.ENVIRONMENT }} || terraform workspace new ${{ env.ENVIRONMENT }}
        working-directory: ${{ vars.ENVIRONMENT }}

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file="${{ env.ENVIRONMENT }}.tfvars"
        working-directory: ${{ vars.ENVIRONMENT }}

      # Optional: Apply Terraform if needed
      # - name: Terraform Apply
      #   run: terraform apply -var-file="${{ env.ENVIRONMENT }}.tfvars" -auto-approve
      #   working-directory: ${{ vars.ENVIRONMENT }}